version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: test_backend_postgres_container
    environment:
      POSTGRES_USER: dinheirow
      POSTGRES_PASSWORD: t3st-back3nd
      POSTGRES_DB: dinheirow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
