version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11
    container_name: pokemon_go_dabatase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./data/db:/var/lib/postgresql/data