version: '3'

services:
  app:
    build: .
    networks:
      - net-bridge
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=db-dinheirow
      - DB_SYNCHRONIZE=true
      - DB_LOGGING=true
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    networks:
      - net-bridge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db-dinheirow
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password

networks:
  net-bridge:
    driver: bridge
  