-- CreateTable
CREATE TABLE "Pokemon" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "pokedexNumber" INTEGER NOT NULL,
    "imgName" INTEGER NOT NULL,
    "generation" INTEGER NOT NULL,
    "evolutionStage" INTEGER NOT NULL,
    "evolved" BOOLEAN NOT NULL,
    "familyId" INTEGER NOT NULL,
    "crossGen" BOOLEAN NOT NULL,
    "type1" VARCHAR(255) NOT NULL,
    "type2" VARCHAR(255) NOT NULL DEFAULT '',
    "weather1" VARCHAR(255) NOT NULL,
    "weather2" VARCHAR(255) NOT NULL DEFAULT '',
    "statTotal" INTEGER NOT NULL,
    "atk" INTEGER NOT NULL,
    "def" INTEGER NOT NULL,
    "sta" INTEGER NOT NULL,
    "legendary" BOOLEAN NOT NULL,
    "aquireable" BOOLEAN NOT NULL,
    "spawns" BOOLEAN NOT NULL,
    "regional" BOOLEAN NOT NULL,
    "raidable" BOOLEAN NOT NULL,
    "hatchable" INTEGER NOT NULL,
    "shiny" BOOLEAN NOT NULL,
    "nest" BOOLEAN NOT NULL,
    "new" BOOLEAN NOT NULL,
    "notGettable" BOOLEAN NOT NULL,
    "futureEvolve" BOOLEAN NOT NULL,
    "MaxCpAt40" INTEGER NOT NULL,
    "MaxCpAt39" INTEGER NOT NULL,

    CONSTRAINT "Pokemon_pkey" PRIMARY KEY ("id")
);
