-- CreateTable
CREATE TABLE `Pokemon` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `row` INTEGER NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `pokedex_number` INTEGER NOT NULL,
    `img_name` INTEGER NOT NULL,
    `generation` INTEGER NOT NULL,
    `evolution_stage` INTEGER NOT NULL,
    `evolved` INTEGER NULL,
    `family_id` INTEGER NULL,
    `cross_gen` INTEGER NOT NULL,
    `type_1` VARCHAR(191) NOT NULL,
    `type_2` VARCHAR(191) NULL,
    `weather_1` VARCHAR(191) NOT NULL,
    `weather_2` VARCHAR(191) NULL,
    `stat_total` INTEGER NOT NULL,
    `atk` INTEGER NOT NULL,
    `def` INTEGER NOT NULL,
    `sta` INTEGER NOT NULL,
    `legendary` INTEGER NOT NULL,
    `aquireable` INTEGER NOT NULL,
    `spawns` INTEGER NULL,
    `regional` INTEGER NOT NULL,
    `raidable` INTEGER NOT NULL,
    `hatchable` INTEGER NOT NULL,
    `shiny` INTEGER NOT NULL,
    `nest` INTEGER NOT NULL,
    `new` INTEGER NOT NULL,
    `not_gettable` INTEGER NOT NULL,
    `future_evolve` INTEGER NOT NULL,
    `cp_40` INTEGER NOT NULL,
    `cp_39` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
