apiVersion: v1
kind: Service
metadata:
  name: poke-api
  labels:
    app: poke-api
spec:
  type: LoadBalancer
  selector:
    app: poke-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP