name: Deploy production
on: 
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Create env file
        run: echo ${{ secrets.Production }} > .env
      - name: Show envs
        run: |
          if [ "$DOCKERHUB_USERNAME" -eq 'henricker']
          then
            echo "It's me"
            echo "It's $DOCKERHUB_USERNAME"
          else
            echo "It's not me"
            echo "It's $DOCKERHUB_USERNAME"
          fi
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push to registry
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./k8s/Dockerfile
      #     push: true
      #     tags: henricker/pokemon-api:latest
